In [1]:
import numpy as np
import pandas as pd
from scipy import stats

In [3]:
df = pd.read_csv('pines.txt', sep='\t')

In [10]:
ret = stats.binned_statistic_2d(df.loc[:, 'sn'], df.loc[:, 'we'], None, 'count', bins=[5, 5])
print(ret.statistic)
print(np.mean(ret.statistic))

[[18. 26. 29. 25. 20.]
 [14. 12. 22. 34. 25.]
 [12. 24. 15. 50. 37.]
 [ 8. 19. 31. 50.  7.]
 [ 7.  8. 37. 27. 27.]]
23.36


In [41]:
data_real = ret.statistic.ravel()
data_theor = np.ones((1, 25)) * 23.36
stats.chisquare(ret.statistic, ddof=0, axis=None)

Power_divergenceResult(statistic=150.58904109589042, pvalue=2.574669774967279e-20)